Add world build stage
Most platforms (ARM, PPC) will fail to build, so just add
non-T-Platforms MIPS boards.  They have a chance to be fixed, maybe.
If we decide to go upstream, we will use U-Boot 2019, not 2014. So,
world build stage pass is not that important.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -12,8 +12,7 @@ stages:
   - testsuites
   - test.py
   - tplatforms build
-# NDZ disable for now, takes too long
-#  - world build
+  - world build
 
 # 129 is returned for warnings, so ignore them for now
 build ours:
@@ -23,7 +22,7 @@ build ours:
     - ret=0;
      ./tools/buildman/buildman -o . -k tplatforms || ret=$?;
      if [[ $ret -ne 0 && $ret -ne 129 ]]; then
-       ./tools/buildman/buildman -o .. -sde;
+       ./tools/buildman/buildman -o . -sde;
        exit $ret;
      fi;
   artifacts:
@@ -63,3 +62,62 @@ Check for configs without MAINTAINERS entry:
   script:
     - if [ `./tools/genboardscfg.py -f 2>&1 | wc -l` -ne 0 ]; then exit 1; fi
 
+build non-TP MIPS platforms:
+  tags: [ 'all' ]
+  stage: world build
+  script:
+    - ret=0;
+     ./tools/buildman/buildman -o /tmp -k mips -x tplatforms || ret=$?;
+     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
+       ./tools/buildman/buildman -o /tmp -sde mips -x tplatforms;
+       exit $ret;
+     fi;
+
+# These platforms fail to build.
+
+#build all 32bit ARM platforms:
+#  tags: [ 'all' ]
+#  stage: world build
+#  script:
+#    - ret=0;
+#     ./tools/buildman/buildman -o /tmp -k arm -x aarch64 || ret=$?;
+#     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
+#       ./tools/buildman/buildman -o /tmp -sde;
+#       exit $ret;
+#     fi;
+#
+#build all 64bit ARM platforms:
+#  tags: [ 'all' ]
+#  stage: world build
+#  script:
+#    - virtualenv /tmp/venv
+#    - . /tmp/venv/bin/activate
+#    - pip install pyelftools
+#    - ret=0;
+#     ./tools/buildman/buildman -o /tmp -k aarch64 || ret=$?;
+#     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
+#       ./tools/buildman/buildman -o /tmp -sde;
+#       exit $ret;
+#     fi;
+#
+#build all PowerPC platforms:
+#  tags: [ 'all' ]
+#  stage: world build
+#  script:
+#    - ret=0;
+#     ./tools/buildman/buildman -o /tmp -k powerpc || ret=$?;
+#     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
+#       ./tools/buildman/buildman -o /tmp -sde;
+#       exit $ret;
+#     fi;
+#
+#build all other platforms:
+#  tags: [ 'all' ]
+#  stage: world build
+#  script:
+#    - ret=0;
+#     ./tools/buildman/buildman -o /tmp -k -x arm,powerpc || ret=$?;
+#     if [[ $ret -ne 0 && $ret -ne 129 ]]; then
+#       ./tools/buildman/buildman -o /tmp -sde;
+#       exit $ret;
+#     fi;
